name: ci ğŸ””
on:
    push:
        branches: 
        - main
        paths:
        - src/*
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout æ‹‰å–ä»£ç 
          uses: actions/checkout@v3
        
        - name: å®‰è£…node
          uses: actions/setup-node@v3
        
        - name: Install dependencies ä¸‹è½½ä¾èµ–
          run: npm install

        - name: Build project æ„å»ºé¡¹ç›®
          run: npm run docs:build
